
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Dec 30 11:33:53 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATER_OR_EQUAL = 23;
  public static final int CONST = 7;
  public static final int CHAR = 2;
  public static final int MINUS_MINUS = 29;
  public static final int NOT_EQUAL_COMPARATION = 21;
  public static final int CASE = 15;
  public static final int TERNARY = 31;
  public static final int LPAREN = 38;
  public static final int SEMI = 37;
  public static final int GREATER = 22;
  public static final int CONTINUE = 14;
  public static final int LESS = 24;
  public static final int MINUS = 16;
  public static final int RPAREN = 39;
  public static final int AND = 26;
  public static final int LESS_OR_EQUAL = 25;
  public static final int OR = 27;
  public static final int COMMA = 42;
  public static final int CLASS = 5;
  public static final int DIV = 18;
  public static final int PLUS = 41;
  public static final int IF = 49;
  public static final int DOT = 30;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int RETURN = 40;
  public static final int PLUS_PLUS = 28;
  public static final int EQUAL = 33;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int MUL = 17;
  public static final int NUMBER = 47;
  public static final int MOD = 19;
  public static final int IDENT = 48;
  public static final int BREAK = 4;
  public static final int RSQUARE_BRACKET = 46;
  public static final int VOID = 44;
  public static final int SWITCH = 8;
  public static final int COLON = 32;
  public static final int ELSE = 50;
  public static final int LBRACE = 35;
  public static final int ENUM = 6;
  public static final int READ = 12;
  public static final int WHILE = 10;
  public static final int RBRACE = 36;
  public static final int EXTENDS = 13;
  public static final int PROG = 34;
  public static final int EQUAL_COMPARATION = 20;
  public static final int LSQUARE_BRACKET = 45;
  public static final int PRINT = 43;
  public static final int DO = 9;
}

