
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 08 22:56:20 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATER_OR_EQUAL = 29;
  public static final int CHAR = 49;
  public static final int CONST = 9;
  public static final int MINUS_MINUS = 34;
  public static final int TERNARY = 39;
  public static final int NOT_EQUAL_COMPARATION = 26;
  public static final int CASE = 11;
  public static final int LPAREN = 42;
  public static final int SEMI = 38;
  public static final int GREATER = 27;
  public static final int CONTINUE = 4;
  public static final int LESS = 28;
  public static final int MINUS = 20;
  public static final int RPAREN = 43;
  public static final int AND = 31;
  public static final int LESS_OR_EQUAL = 30;
  public static final int OR = 32;
  public static final int COMMA = 36;
  public static final int CLASS = 6;
  public static final int DIV = 22;
  public static final int PLUS = 19;
  public static final int IF = 14;
  public static final int DOT = 35;
  public static final int BOOLEAN = 50;
  public static final int EOF = 0;
  public static final int RETURN = 46;
  public static final int PLUS_PLUS = 33;
  public static final int EQUAL = 24;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int MUL = 21;
  public static final int NUMBER = 47;
  public static final int MOD = 23;
  public static final int IDENT = 48;
  public static final int BREAK = 3;
  public static final int RSQUARE_BRACKET = 45;
  public static final int VOID = 5;
  public static final int SWITCH = 10;
  public static final int COLON = 37;
  public static final int LBRACE = 40;
  public static final int ELSE = 15;
  public static final int ENUM = 8;
  public static final int READ = 17;
  public static final int WHILE = 13;
  public static final int RBRACE = 41;
  public static final int EXTENDS = 7;
  public static final int PROG = 2;
  public static final int EQUAL_COMPARATION = 25;
  public static final int LSQUARE_BRACKET = 44;
  public static final int PRINT = 18;
  public static final int DO = 12;
}

